apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usuarios
  template:
    metadata:
      labels:
        app: usuarios
    spec:
      containers:
      - image: julsorio/udemy-docker-usuarios:v1
        name: udemy-docker-usuarios
        ports:
        - containerPort: 8001
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: test
