apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres14
  template:
    metadata:
      labels:
        app: postgres14
    spec:
      containers:
      - image: postgres:14-alpine
        name: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-db-cursos
                key: password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: db-cursos
                key: database
        volumeMounts: 
          - name: data-postgres
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: postgres-pvc
