apiVersion: v1
kind: Secret
metadata:
  name: secret-db-usuarios
type: Opaque
data:
  password: c2FzYQ==
  
---

apiVersion: v1
kind: Secret
metadata:
  name: secret-db-cursos
type: Opaque
data:
  password: c2FzYQ==